name: publish-nuget

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: actions/checkout@v2
            
    - name: Run build & publish
      run: ./build.ps1
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
